### ISSUE TITLE
Provide more info to YunoHost admin

### ISSUE THREAD

**Issue by anaqreon** [YunoHost-Apps/hubzilla_ynh#11]
We need to inform the YunoHost admin about the system-wide changes to php.ini including the enabling of exec() and the increase of upload size. We should add the upload size as an installation option.

**Comment by anaqreon** [comment]
https://github.com/YunoHost-Apps/hubzilla-yunohost/tree/2.0.7

**Comment by anmol26s** [comment]
Will have to check why there is need to add `client_max_body_size= ;` to the server {} block instead of location {} block when all other YunoHost app work fine with adding the limit to the location {} block.
Maybe its only with my YunoHost instance(I might have changed something in the nginx which I don't remember).

**Comment by anmol26s** [comment]
The app don't use its own php configuration now and system wide configuration is not required now.
Closing.
