### ISSUE TITLE
WebDAV and CalDAV

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/hubzilla_ynh#28]
For some reason i can´t get WebDAV and CalDAV to work. Don´t know why maybe its my DNS settings. Has someone with HZ on yunohost got it working?

**Comment by anmol26s** [comment]
Is the problem still persists?

**Comment by rocky-III** [comment]
I will check again... but can´t do it today

**Comment by anmol26s** [comment]
No problem, take your time.

**Comment by anmol26s** [comment]
Helloo,

Did you tried it again ? WebDav and CalDav is an amazing feature which Hubzilla offers. Though I never used it on Hubzilla. This should be tested and fixed  because this is what makes Hubzilla  way better then any other Fediverse player.  I am planning to shift from Baikal to some other WebDav or CalDav app. Hopefully it will be Nextcloud or Hubzilla.

**Comment by anmol26s** [comment]
Webdav and carddav works for me. I think caldav will work too. So this can be closed.
